// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package bcn

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLawClient creates a new instance of MockLawClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLawClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLawClient {
	mock := &MockLawClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLawClient is an autogenerated mock type for the LawClient type
type MockLawClient struct {
	mock.Mock
}

type MockLawClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLawClient) EXPECT() *MockLawClient_Expecter {
	return &MockLawClient_Expecter{mock: &_m.Mock}
}

// GetNorma provides a mock function for the type MockLawClient
func (_mock *MockLawClient) GetNorma(ctx context.Context, normID int64) (NormaFull, error) {
	ret := _mock.Called(ctx, normID)

	if len(ret) == 0 {
		panic("no return value specified for GetNorma")
	}

	var r0 NormaFull
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (NormaFull, error)); ok {
		return returnFunc(ctx, normID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) NormaFull); ok {
		r0 = returnFunc(ctx, normID)
	} else {
		r0 = ret.Get(0).(NormaFull)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, normID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLawClient_GetNorma_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNorma'
type MockLawClient_GetNorma_Call struct {
	*mock.Call
}

// GetNorma is a helper method to define mock.On call
//   - ctx context.Context
//   - normID int64
func (_e *MockLawClient_Expecter) GetNorma(ctx any, normID any) *MockLawClient_GetNorma_Call {
	return &MockLawClient_GetNorma_Call{Call: _e.mock.On("GetNorma", ctx, normID)}
}

func (_c *MockLawClient_GetNorma_Call) Run(run func(ctx context.Context, normID int64)) *MockLawClient_GetNorma_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLawClient_GetNorma_Call) Return(normaFull NormaFull, err error) *MockLawClient_GetNorma_Call {
	_c.Call.Return(normaFull, err)
	return _c
}

func (_c *MockLawClient_GetNorma_Call) RunAndReturn(run func(ctx context.Context, normID int64) (NormaFull, error)) *MockLawClient_GetNorma_Call {
	_c.Call.Return(run)
	return _c
}

// GetNormaSummary provides a mock function for the type MockLawClient
func (_mock *MockLawClient) GetNormaSummary(ctx context.Context, normID int64) (NormaSummary, error) {
	ret := _mock.Called(ctx, normID)

	if len(ret) == 0 {
		panic("no return value specified for GetNormaSummary")
	}

	var r0 NormaSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (NormaSummary, error)); ok {
		return returnFunc(ctx, normID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) NormaSummary); ok {
		r0 = returnFunc(ctx, normID)
	} else {
		r0 = ret.Get(0).(NormaSummary)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, normID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLawClient_GetNormaSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNormaSummary'
type MockLawClient_GetNormaSummary_Call struct {
	*mock.Call
}

// GetNormaSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - normID int64
func (_e *MockLawClient_Expecter) GetNormaSummary(ctx any, normID any) *MockLawClient_GetNormaSummary_Call {
	return &MockLawClient_GetNormaSummary_Call{Call: _e.mock.On("GetNormaSummary", ctx, normID)}
}

func (_c *MockLawClient_GetNormaSummary_Call) Run(run func(ctx context.Context, normID int64)) *MockLawClient_GetNormaSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLawClient_GetNormaSummary_Call) Return(normaSummary NormaSummary, err error) *MockLawClient_GetNormaSummary_Call {
	_c.Call.Return(normaSummary, err)
	return _c
}

func (_c *MockLawClient_GetNormaSummary_Call) RunAndReturn(run func(ctx context.Context, normID int64) (NormaSummary, error)) *MockLawClient_GetNormaSummary_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockLawClient
func (_mock *MockLawClient) Search(ctx context.Context, params SearchParams) (SearchResponse, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 SearchResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, SearchParams) (SearchResponse, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, SearchParams) SearchResponse); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(SearchResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, SearchParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLawClient_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockLawClient_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - params SearchParams
func (_e *MockLawClient_Expecter) Search(ctx any, params any) *MockLawClient_Search_Call {
	return &MockLawClient_Search_Call{Call: _e.mock.On("Search", ctx, params)}
}

func (_c *MockLawClient_Search_Call) Run(run func(ctx context.Context, params SearchParams)) *MockLawClient_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 SearchParams
		if args[1] != nil {
			arg1 = args[1].(SearchParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLawClient_Search_Call) Return(searchResponse SearchResponse, err error) *MockLawClient_Search_Call {
	_c.Call.Return(searchResponse, err)
	return _c
}

func (_c *MockLawClient_Search_Call) RunAndReturn(run func(ctx context.Context, params SearchParams) (SearchResponse, error)) *MockLawClient_Search_Call {
	_c.Call.Return(run)
	return _c
}
