// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cgr

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCgrClient creates a new instance of MockCgrClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCgrClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCgrClient {
	mock := &MockCgrClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCgrClient is an autogenerated mock type for the CgrClient type
type MockCgrClient struct {
	mock.Mock
}

type MockCgrClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCgrClient) EXPECT() *MockCgrClient_Expecter {
	return &MockCgrClient_Expecter{mock: &_m.Mock}
}

// CountJurisprudencia provides a mock function for the type MockCgrClient
func (_mock *MockCgrClient) CountJurisprudencia(ctx context.Context, query string, exactSearch bool) (CountResponse, error) {
	ret := _mock.Called(ctx, query, exactSearch)

	if len(ret) == 0 {
		panic("no return value specified for CountJurisprudencia")
	}

	var r0 CountResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) (CountResponse, error)); ok {
		return returnFunc(ctx, query, exactSearch)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) CountResponse); ok {
		r0 = returnFunc(ctx, query, exactSearch)
	} else {
		r0 = ret.Get(0).(CountResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = returnFunc(ctx, query, exactSearch)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCgrClient_CountJurisprudencia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountJurisprudencia'
type MockCgrClient_CountJurisprudencia_Call struct {
	*mock.Call
}

// CountJurisprudencia is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - exactSearch bool
func (_e *MockCgrClient_Expecter) CountJurisprudencia(ctx any, query any, exactSearch any) *MockCgrClient_CountJurisprudencia_Call {
	return &MockCgrClient_CountJurisprudencia_Call{Call: _e.mock.On("CountJurisprudencia", ctx, query, exactSearch)}
}

func (_c *MockCgrClient_CountJurisprudencia_Call) Run(run func(ctx context.Context, query string, exactSearch bool)) *MockCgrClient_CountJurisprudencia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCgrClient_CountJurisprudencia_Call) Return(countResponse CountResponse, err error) *MockCgrClient_CountJurisprudencia_Call {
	_c.Call.Return(countResponse, err)
	return _c
}

func (_c *MockCgrClient_CountJurisprudencia_Call) RunAndReturn(run func(ctx context.Context, query string, exactSearch bool) (CountResponse, error)) *MockCgrClient_CountJurisprudencia_Call {
	_c.Call.Return(run)
	return _c
}

// GetDictamen provides a mock function for the type MockCgrClient
func (_mock *MockCgrClient) GetDictamen(ctx context.Context, dictamenID string) (DictamenFull, error) {
	ret := _mock.Called(ctx, dictamenID)

	if len(ret) == 0 {
		panic("no return value specified for GetDictamen")
	}

	var r0 DictamenFull
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (DictamenFull, error)); ok {
		return returnFunc(ctx, dictamenID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) DictamenFull); ok {
		r0 = returnFunc(ctx, dictamenID)
	} else {
		r0 = ret.Get(0).(DictamenFull)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, dictamenID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCgrClient_GetDictamen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDictamen'
type MockCgrClient_GetDictamen_Call struct {
	*mock.Call
}

// GetDictamen is a helper method to define mock.On call
//   - ctx context.Context
//   - dictamenID string
func (_e *MockCgrClient_Expecter) GetDictamen(ctx any, dictamenID any) *MockCgrClient_GetDictamen_Call {
	return &MockCgrClient_GetDictamen_Call{Call: _e.mock.On("GetDictamen", ctx, dictamenID)}
}

func (_c *MockCgrClient_GetDictamen_Call) Run(run func(ctx context.Context, dictamenID string)) *MockCgrClient_GetDictamen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCgrClient_GetDictamen_Call) Return(dictamenFull DictamenFull, err error) *MockCgrClient_GetDictamen_Call {
	_c.Call.Return(dictamenFull, err)
	return _c
}

func (_c *MockCgrClient_GetDictamen_Call) RunAndReturn(run func(ctx context.Context, dictamenID string) (DictamenFull, error)) *MockCgrClient_GetDictamen_Call {
	_c.Call.Return(run)
	return _c
}

// SearchDictamenes provides a mock function for the type MockCgrClient
func (_mock *MockCgrClient) SearchDictamenes(ctx context.Context, params SearchParams) (SearchResponse, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for SearchDictamenes")
	}

	var r0 SearchResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, SearchParams) (SearchResponse, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, SearchParams) SearchResponse); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(SearchResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, SearchParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCgrClient_SearchDictamenes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchDictamenes'
type MockCgrClient_SearchDictamenes_Call struct {
	*mock.Call
}

// SearchDictamenes is a helper method to define mock.On call
//   - ctx context.Context
//   - params SearchParams
func (_e *MockCgrClient_Expecter) SearchDictamenes(ctx any, params any) *MockCgrClient_SearchDictamenes_Call {
	return &MockCgrClient_SearchDictamenes_Call{Call: _e.mock.On("SearchDictamenes", ctx, params)}
}

func (_c *MockCgrClient_SearchDictamenes_Call) Run(run func(ctx context.Context, params SearchParams)) *MockCgrClient_SearchDictamenes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 SearchParams
		if args[1] != nil {
			arg1 = args[1].(SearchParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCgrClient_SearchDictamenes_Call) Return(searchResponse SearchResponse, err error) *MockCgrClient_SearchDictamenes_Call {
	_c.Call.Return(searchResponse, err)
	return _c
}

func (_c *MockCgrClient_SearchDictamenes_Call) RunAndReturn(run func(ctx context.Context, params SearchParams) (SearchResponse, error)) *MockCgrClient_SearchDictamenes_Call {
	_c.Call.Return(run)
	return _c
}
